{{- if and .Values.istio.enabled .Values.istio.hardened.enabled -}}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-prometheus-to-policy-reporter
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels: 
      app.kubernetes.io/name: policy-reporter
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/monitoring/sa/monitoring-monitoring-kube-prometheus"]
    to:
    - operation:
        methods: ["GET"]
        paths: ["/metrics"]
        ports: ["8080"]
{{- end }}
