{{- if and .Values.istio.enabled .Values.istio.hardened.enabled -}}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-ui-to-policy-reporter-port
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels: 
      app.kubernetes.io/name: policy-reporter-ui
  action: ALLOW
  rules:
  - to:
    - operation:
        ports: 
        - "{{ .Values.upstream.service.port }}"
{{- end }}
