{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-dns
  namespace: {{ .Release.Namespace }}
  labels: {{ include "policyreporter.labels" . | nindent 4 }}
spec:
  egress:
  - to:
    - namespaceSelector: {}
    ports:
    - port: 53
      protocol: UDP
    {{- if .Values.openshift }}
    - port: 5353
      protocol: UDP
    {{- end }}
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: policy-reporter
  policyTypes:
  - Egress
{{- end }}