{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-egress-default-deny
  namespace: {{ .Release.Namespace }}
  labels: {{ include "policyreporter.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: policy-reporter
  policyTypes:
  - Ingress
  - Egress
  ingress: []
  egress: []
{{- end }}
